<?php

return array(
    //<editor-fold defaultstate="collapsed" desc="菜单面板">
    'MENUMOBAN' => array(
        'title' => array('des' => '菜单名称',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
         'shorttitle' => array('des' => '短标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => ''
        ),
        'viewpath' => array('des' => '链接',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'datatype' => array('des' => '数据类型',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 'controller',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'datatype',
//            ),
        ),
        'viewmod' => array('des' => '菜单标签','placeholder' => '有定位需求时使用',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'groupmark' => array('des' => '导航分组标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'parentid' => array('des' => '上级菜单',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'mod' => 'NotSelf',
            'listtopid' => 0,
            'listtopname' => '顶级菜单',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\Model\MenuModel',
            ),
        ),

        'shownav' => array('des' => '菜单显示',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 1,
             'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'menuShow',
            ),
        ),
        'menutype' => array('des' => '菜单类型',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'menutype',
            ),
        ),
        'target' => array('des' => '打开方式',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '_self',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'linkTarget',
            ),            
        ),
        'shortcut' => array('des' => '快捷菜单',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 0,
             'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),               
        ),
        'isshow' => array('des' => '显示',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),     
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="栏目面板">
    'COLUMNSPANEL' => array(
        'title' => array('des' => '菜单名称',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'shorttitle' => array('des' => '短标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => ''
        ),
         'keyword' => array('des' => '关键字',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
//        'summary' => array('des' => '描述',
//            'tableindex' => 'langue',
//            'model' => 'text',
//            'value' => ''
//        ),
        
        'viewpath' => array('des' => '栏目标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
    
        'groupmark' => array('des' => '分组标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'viewmod' => array('des' => '显示模板',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'parentid' => array('des' => '所属栏目',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'search' => 'lay-search',
            'mod' => 'NotSelf',
            'listtopid' => 0,
            'listtopname' => '根栏目',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\News\ColumnsModel',
            ),
        ),
         'istopic' => array('des' => '分区号',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),
//        'lev' => array('des' => '栏目类型',
//            'tableindex' => 'tableCart_base',
//            'model' => 'rdlist',
//            'value' => 2,
//             'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'columnstype',
//            ),
//        ),
        'shownav' => array('des' => '位置显示',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'menuShow',
            ),
        ),
//        'showlist' => array('des' => '可扩展',
//            'model' => 'rdlist',
//            'tableindex' => 'tableCart_base',
//            'value' => '0',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'tagmark' => 'YesNo',
//                'sourcetyp' => 'attrmap',
//            ),
//        ),
        'isshow' => array('des' => '状态',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),

//        'viewmod' => array(
//             'tableindex' => 'tableCart_base',
//            'des' => '输入模板',
//             'model' => 'rdlist',
//            'value' => 3,
//             'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'news_inputpanel',
//            ),           
//            'value' => 'BASEPANEL',
//        ),
//        'homepage' => array('des' => '首页模板',
//            'tableindex' => 'tableCart_base',
//            'model' => 'dropdown',
//            'listtopid' => 0,
//            'listtopname' => '默认模板',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'table' => 'theme',
//            ),
//            'value' => ''
//        ),
//        'listmod' => array('des' => '列表模板',
//            'tableindex' => 'tableCart_base',
//            'model' => 'dropdown',
//            'listtopid' => 0,
//            'listtopname' => '默认模板',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'table' => 'theme',
//            ),
//            'value' => ''
//        ),
//        'pagemod' => array('des' => '详情模板',
//            'tableindex' => 'tableCart_base',
//            'model' => 'dropdown',
//            'listtopid' => 0,
//            'listtopname' => '默认模板',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'table' => 'theme',
//            ),
//            'value' => ''
//        ),
        'pagesize' => array('des' => '分页数',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
           'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="单页面板">
    'SINGLEPANEL' => array(
        'title' => array('des' => '菜单名称',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'shorttitle' => array('des' => '短标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => ''
        ),
         'keyword' => array('des' => '关键字',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'content' => array('des' => '详情',
            'tableindex' => 'langue',
            'model' => 'edit',
            'value' => ''
        ),
        
        'viewpath' => array('des' => '栏目标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
    
        'groupmark' => array('des' => '分组标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'parentid' => array('des' => '所属栏目',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'search' => 'lay-search',
            'mod' => 'NotSelf',
            'listtopid' => 0,
            'listtopname' => '根栏目',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\News\ColumnsModel',
            ),
        ),
         'istopic' => array('des' => '分区号',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),

        'shownav' => array('des' => '位置显示',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'menuShow',
            ),
        ),
        'isshow' => array('des' => '审核',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
        'pagesize' => array('des' => '分页数',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),
           'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="文章输入模版">
    'BASEPANEL' => array(
        'page_title' => array('des' => '标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'subtitle' => array('des' => '副标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'short' => array('des' => '标签', 'des2' => '限四字，首页有效',
            'tableindex' => 'langue',
            'model' => 'hidden',
            'value' => ''
        ),        
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'hidden',
            'value' => ''
        ),
        'description' => array('des' => '描述',
            'tableindex' => 'langue',
            'model' => 'hidden',
            'value' => ''
        ),
        
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'value' => '',
             'inputtype'=>'hidden'
        ),
//        'keyword' => array('des' => '关键字',
//            'tableindex' => 'langue',
//            'model' => 'input',
//            'value' => ''
//        ),
        'content' => array('des' => '文章内容',
            'tableindex' => 'langue',
            'model' => 'edit',
            'value' => ''
        ),
        
        'colid' => array('des' => '栏目',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'mod' => 'FinalNode',
            'cls' => 'changemod',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\News\ColumnsModel',
            ),
        ),
//        'extcol' => array('des' => '扩展栏目',
//            'tableindex' => 'tableCart_base',
//            'model' => 'cklist',
//            'source' => array(
//                'idfiled' => 'id',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'map',
//            ),
//            'value' => ''
//        ),
//        'pic' => array('des' => '上传附件',
//            'tableindex' => 'tableCart_base',
//            'model' => 'file',
//            'value' => ''
//        ),
        'originaltitle' => array('des' => '文章来源',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
//              'authorsys' => array('des' => '作者系统占位符',
//            'model' => 'hidden',
//            'value' => '0'
//        ),
        'exturl' => array('des' => '外部链接',
          'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
//        'summary' => array('des' => '标签',
//            'tableindex' => 'tableCart_base',
//            'model' => 'cklist',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'news_tag',
//            ),
//            'value' => ''
//        ),
        'poster' => array('des' => '作者',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => 'admin',
        ),
        'hits' => array('des' => '浏览量',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),
        'posttime' => array('des' => '发布时间',
            'tableindex' => 'tableCart_base',
            'model' => 'datepicker',
            'dateformat' => array('type' => 'datetime', 'format' => 'yyyy-MM-dd HH:mm:ss' ,'trancemat' => 'Y-m-d H:i:s'),
            'width' => '120',
            'value' => time(),
        ),
        'attr' => array('des' => '属性',
            'tableindex' => 'tableCart_base',
            'model' => 'attrcklist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'news_attrlist',
            ),
            'value' => '0'
        ),
        'isshow' => array('des' => '审核状态',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '0'
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>   
    
    //<editor-fold defaultstate="collapsed" desc="章节模版">
    'NOTEPANEL' => array(
        'title' => array('des' => '标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'content' => array('des' => '文章内容',
            'tableindex' => 'langue',
            'model' => 'edit',
            'value' => ''
        ),
        'bookid' => array('des' => '小说',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'tags' => array('des' => '标签',
          'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),     
        'hits' => array('des' => '浏览量',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => 0
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),   
      
        'ischapter' => array('des' => '章回',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => 0
        ),
        'url' => array('des' => 'url',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ""
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold> 
);
