<?php

return array(
//<editor-fold defaultstate="collapsed" desc="修改头像昵称">
    'HEADPICPANLE' => array(
        'username' => array('des' => '用户名',
            'tableindex' => 'base',
            'model' => 'input',
            'width' => 200,
            'readonly' => 2,
            'value' => '',
        ),
        'nickname' => array('des' => '昵称',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'readonly' => 2,
            'value' => '',
        ),
        'thumb' => array('des' => '头像', 'des2' => '参考尺寸：120 * 120',
            'model' => 'image',
            'vouchratio'=>'1',//推荐裁剪比例
            'onlyvouchratio'=>'1',//强制裁剪比例
            'value' => '',
            'inputtype'=>'hidden'
        ),
    ),
//</editor-fold>   
//<editor-fold defaultstate="collapsed" desc="前台用户注册模板">
    'REGPANLE' => array(
        'username' => array('des' => '用户名',
            'model' => 'input',
            'width' => 200,
//            'readonly' => 1,
            'value' => '',
        ),
        'nickname' => array('des' => '昵称',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'gender' => array('des' => '性别',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gender',
            ),
            'tableindex' => 'base',
        ),
        'password' => array('des' => '密码',
            'model' => 'password',
            'width' => 200,
            'value' => ''
        ),
        'repassword' => array('des' => '确认密码',
            'model' => 'password',
            'width' => 200,
            'value' => ''
        ),
    ),
    //</editor-fold>   
//<editor-fold defaultstate="collapsed" desc="前台用户资料修改">
    'USERINFO' => array(
        'username' => array('des' => '用户名',
            'tableindex' => 'base',
            'model' => 'input',
            'width' => 200,
            'readonly' => 2,
            'value' => '',
        ),
        'nickname' => array('des' => '昵称',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'email' => array('des' => '邮箱',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'gender' => array('des' => '性别',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gender',
            ),
            'tableindex' => 'base',
        ),
    ),
    //</editor-fold> 
//<editor-fold defaultstate="collapsed" desc="前台找回密码1">
    'FORGETPANLE1' => array(
        'username' => array('des' => '用户名',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'email' => array('des' => '邮箱',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
    ),
    //</editor-fold>  
//<editor-fold defaultstate="collapsed" desc="修改密码">
    'SETNEWPASSW' => array(
         'oldpassword' => array('des' => '原密码',
            'model' => 'password',
            'verify'=>'required',
            'width' => 200,
            'value' => ''
        ),
        'password' => array('des' => '密码',
            'model' => 'password',
            'verify'=>'required',
            'width' => 200,
            'value' => ''
        ),
        'repassword' => array('des' => '确认密码',
            'model' => 'password',
            'verify'=>'required',
            'width' => 200,
            'value' => ''
        ),
    ),
//</editor-fold> 
//<editor-fold defaultstate="collapsed" desc="密码重置">
    'RESETPANLE' => array(
        'password' => array('des' => '密码',
            'model' => 'password',
            'width' => 200,
            'value' => ''
        ),
        'repassword' => array('des' => '确认密码',
            'model' => 'password',
            'width' => 200,
            'value' => ''
        ),
    ),
    //</editor-fold>   
//<editor-fold defaultstate="collapsed" desc="前台用户输入模板">
    'USERDETAIL' => array(
        'username' => array('des' => '用户名',
            'model' => 'input',
            'width' => 200,
            'readonly' => 2,
            'value' => '',
        ),
        'nickname' => array('des' => '昵称',
            'model' => 'input',
            'readonly' => 2,
            'width' => 200,
            'value' => '',
        ),
        'password' => array('des' => '密码',
            'model' => 'password',
            'width' => 200,
            'value' => ''
        ),
        'email' => array('des' => '邮箱',
            'model' => 'input',
            'readonly' => 2,
            'width' => 200,
            'value' => '',
        ),
        'gender' => array('des' => '性别',
            'model' => 'rdlist',
            'readonly' => 2,
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gender',
            ),
        ),
    ),
        //</editor-fold>   

//<editor-fold defaultstate="collapsed" desc="实名资料填写">
    /**
     * 企业实名
     */
    'REALNAMECRC' => array(
        'modid' => array('des' => '房源类型',
            'titletag' => 'YunyinType',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'yunyintype',
            ),
        ),
        'biz' => array('des' => '商家编号',
            'tableindex' => 'base',
            'model' => 'input',
            'width' => 200,
            'readonly' => 2,
            'value' => '',
        ),
        'company' => array('des' => '企业名称',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'license' => array('des' => '营业执照',
            'model' => 'input',
            'tableindex' => 'base',
            'value' => '',
        ),
        'licensepic' => array('des' => '营业执照',
            'model' => 'image',      
            'tableindex' => 'base',
            'value' => '',
            'inputtype'=>'hidden'
        ),
        'thumb' => array('des' => '形象照片',
            'model' => 'image',   
            'tableindex' => 'base',
            'vouchratio'=>'1',//推荐裁剪比例
            'onlyvouchratio'=>'1',//强制裁剪比例
            'value' => '',
            'inputtype'=>'hidden'
        ),
        'truename' => array('des' => '联系人',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'mobile' => array('des' => '联系电话',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'email' => array('des' => '邮箱',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
    ),
    
    /**
     * 个人实名
     */
    'REALNAMECRC1' => array(
        'modid' => array('des' => '房源类型',
            'titletag' => 'YunyinType',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'yunyintype',
            ),
        ),
        'biz' => array('des' => '商家编号',
            'tableindex' => 'base',
            'model' => 'input',
            'readonly' => 2,
            'value' => '',
        ),            
        'truename' => array('des' => '联系人',
            'model' => 'input',
            'tableindex' => 'base',
            'value' => '',
        ),
        'idcard' => array('des' => '身份证',
            'model' => 'input',
            'tableindex' => 'base',
            'value' => '',
        ),
        'licensepic' => array('des' => '证件照片',
            'model' => 'image',      
            'tableindex' => 'base',
            'value' => '',
            'inputtype'=>'hidden'
        ),
        'thumb' => array('des' => '形象照片',
            'model' => 'image',         
            'tableindex' => 'base',
            'vouchratio' => '1', //推荐裁剪比例
            'onlyvouchratio' => '1', //强制裁剪比例
            'value' => '',
            'inputtype' => 'hidden'
        ),
        'gender' => array('des' => '性别',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gender',
            ),
            'tableindex' => 'base',
        ),
        'mobile' => array('des' => '联系电话',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
        'email' => array('des' => '邮箱',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),        
        'birthday' => array('des' => '生日',
            'model' => 'input',
            'width' => 200,
            'tableindex' => 'base',
            'value' => '',
        ),
    ),
    //</editor-fold> 
    
);
