<?php

return array(
    //<editor-fold defaultstate="collapsed" desc="产品分类">
    'GOODSCAT' => array(
        'parentid' => array('des' => '上级分类',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'mod' => 'NotSelf',//NotSelf
            'listtopid' => 0,
            'listtopname' => '顶级菜单',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\Gmodel\GcateModel',
            ),
            'value' => 0
        ),
         'viewpath' => array('des' => '访问路径',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
          'groupmark' => array('des' => '分组标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
         'shownav' => array('des' => '导航显示',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'menuShow',
            ),
        ),
         'pagelist' => array('des' => '分页数',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
         'datatype' => array('des' => '数据类型',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',//rdlist hidden
            'value' => 'goodstree',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'datatype',
            ),
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
        'isshow' => array('des' => '状态',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),   
        ),
        'title' => array('des' => '标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'shorttitle' => array('des' => '短标题',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'value' => ''
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="产品">
    'GOODS' => array(
        'title' => array('des' => '产品名称',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'value' => ''
        ),
        'keywords' => array('des' => '关键词',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'goods_remark' => array('des' => '商品简单描述',
            'tableindex' => 'langue',
            'model' => 'hidden',
            'value' => ''
        ),
        'content' => array('des' => '商品详细描述',
            'tableindex' => 'langue',
            'model' => 'edit',
            'value' => ''
        ),
//        'original_re' => array('des' => '热卖图片',
//            'tableindex' => 'langue',
//            'model' => 'image',
//            'value' => ''
//        ),
//        'original_tuan' => array('des' => '商品上传原始图',
//            'tableindex' => 'langue',
//            'model' => 'image',
//            'value' => ''
//        ),
//        'original_img' => array('des' => '商品上传原始图',
//            'tableindex' => 'langue',
//            'model' => 'image',
//            'value' => ''
//        ),
          'photolist' => array('des' => '相册',
            'tableindex' => 'tableCart_base2',
            'model' => 'mimage',
            'value' => ''
        ),
        'goods_sn' => array('des' => '商品编号',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'cat_id' => array('des' => '分类',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'mod' => 'FinalNode',
            'listtopid' => '',
            'listtopname' => '选择分类',
            'verifymsg' => '请输入产品分类',     
            'verify' => 'required',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\Gmodel\GcateModel',
            ),
            'value' => ''
        ),
//        'brand_id' => array('des' => '品牌',
//            'tableindex' => 'tableCart_base',
//            'model' => 'modeltree',
//            'mod' => 'all', //FinalNode,all,NotSelf
//            'listtopid' => 0,
//            'listtopname' => '选择品牌',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'dbmodel' => '\Common\Gmodel\AttrsModel',
//                'pmap' => array('tagmark' => 'AboutGoods_brand')
//            ),
//            'value' => 0
//        ),
//         'summary' => array('des' => '标签',
//            'tableindex' => 'tableCart_base',
//            'model' => 'cklist',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'Goodstag',
//            ),
//            'value' => ''
//        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
        'is_on_sale' => array('des' => '上架',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'is_recommend' => array('des' => '推荐',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'is_new' => array('des' => '新品',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'is_hot' => array('des' => '热卖',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'YesNo',
                'sourcetyp' => 'attrmap',
            ),
        ),
//        'extend_cat_id' => array('des' => '扩展分类',
//            'tableindex' => 'tableCart_base',
//            'model' => 'hidden',
//            'value' => 0,
//        ),
        'click_count' => array('des' => '点击数',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'store_count' => array('des' => '库存数量',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'comment_count' => array('des' => '商品评论数',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'weight' => array('des' => '商品重量(克)',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'market_price' => array('des' => '市场价',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ), 'shop_price' => array('des' => '本店价',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ), 'cost_price' => array('des' => '商品成本价',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ), 'is_real' => array('des' => '实物',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'goods_hui' => array('des' => '',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ), 
        'is_free_shipping' => array('des' => '包邮',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ), 'goods_type' => array('des' => '商品所属类型id',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'goods_type' => array('des' => '商品所属类型id',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'spec_type' => array('des' => '商品所属类型id',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'give_integral' => array('des' => '购买商品赠送积分',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'exchange_integral' => array('des' => '积分兑换：0不参与积分兑换，积分和现金的兑换比例100：1',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'suppliers_id' => array('des' => '供货商ID',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'sales_sum' => array('des' => '商品销量',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'prom_type' => array('des' => '0 普通订单,1 限时抢购, 2 团购 , 3 促销优惠',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'prom_id' => array('des' => '优惠活动id',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'commission' => array('des' => '佣金用于分销分成',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'spu' => array('des' => '',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'sku' => array('des' => '',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'market_zhe' => array('des' => '打折',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'goods_youfei' => array('des' => '',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
            "tableCart_base2" => '相册',
        ),
    ),
        //</editor-fold>
);
