<?php

/**
 * @author 默鱼 <feiyufly001@hotmail.com>
 * 网站配置
 */

/**
 * 点赞
 */
const CollectType_Like = 10;

/**
 * 阅读
 */
const CollectType_Read = 20;

/**
 * 评论
 */
const CollectType_Review = 30;

/**
 * 收藏
 */
const CollectType_Favorite = 40;

const UploadFileModSys = 'sys';


return array(
    //<editor-fold defaultstate="collapsed" desc="网站基本配置">
    'SITEBASE' => array(
        'web_title' => array('des' => '网站名字',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'web_keyword' => array('des' => '网站关键字',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'web_description' => array('des' => '网站描述',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'text',
            'value' => ''
        ),
        'sitelogo' => array('des' => 'LOGO',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'image',
            'value' => '',
            'inputtype' => 'hidden'
        ),
        'web_copyright' => array('des' => '版权声明',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'web_welcome' => array('des' => '欢迎词',
            'parentkey' => 'SiteConfig',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'web_site' => array('des' => '网站地址',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_imgserver' => array('des' => '图片地址',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_domain' => array('des' => '域名', 'des2' => '不要带任何前缀',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'siteico' => array('des' => '网站图标',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'image',
            'value' => '',
            'inputtype' => 'hidden'
        ),
        'web_icp' => array('des' => 'ICP备案号',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_gongan' => array('des' => '公安备案号',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'default_lang' => array('des' => '后台语言',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist', //rdlist
            'value' => 'cn',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Langue',
            ),
        ),
        'front_lang' => array('des' => '前台语言',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden', //rdlist
            'value' => 'cn',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Langue',
            ),
        ),
//        'url_router' => array('des' => '启用路由',
//            'tableindex' => 'tableCart_base',
//            'model' => 'switch',
//            'value' => '',           
//        ),
        'web_sign_max' => array('des' => '连续签到数', 'des2' => '最天连续签到积份加成天数',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_list_pagesize' => array('des' => '后台分页数', 'des2' => '后台每页记录数量',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'front_list_pagesize' => array('des' => '前台分页数', 'des2' => '前台每页记录数量',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'news_autocheck' => array('des' => '后台发布审核',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'shorttitle',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'isshow_status',
            ),
        ),
        'user_autocheck' => array('des' => '用户发布审核',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'shorttitle',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'isshow_status',
            ),
        ),
        'news_editcheck' => array('des' => '文章修改审核', 'des2' => '开启后，文章被编辑后，审核状态调整为默认值',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'SiteConfig',
            'model' => 'hidden',
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'enable_tel' => array('des' => '岗位识别', 'des2' => '开启后，管理员根据岗位调整权限',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'enable_post' => array('des' => '全栏目投稿', 'des2' => '开启后，用户可以向所有栏目投稿',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'enable_author' => array('des' => '作者系统', 'des2' => '开启作者系统后，请在“网站设置-->部门管理”中及时添加部门',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'mailer_manager' => array('des' => '客服经理',
            'tableindex' => 'tableCart_email',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'mailer_mail' => array('des' => '客服邮箱',
            'tableindex' => 'tableCart_email',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'mailer_said' => array('des' => '客服称谓',
            'tableindex' => 'tableCart_email',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'mailer_header' => array('des' => '客服头像', 'des2' => '建议尽寸：40 * 40；',
            'tableindex' => 'tableCart_email',
            'parentkey' => 'SiteConfig',
            'model' => 'image',
            'value' => '',
            'inputtype' => 'hidden'
        ),
        'wx_token' => array('des' => '微信 token', 'des2' => '填写你设定的key',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'wx_encodingaeskey' => array('des' => '微信 encodingaeskey', 'des2' => '填写你设定的key',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'wx_appid' => array('des' => '微信 appid', 'des2' => '填写高级调用功能的app id',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'wx_appsecret' => array('des' => '微信 appsecret', 'des2' => '填写高级调用功能的密钥',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'wx_default' => array('des' => '默认回复', 'des2' => '微信公从号默认回复',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'wx_domain' => array('des' => '图片服务器',
            'tableindex' => 'tableCart_wecat',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_tel' => array('des' => '联系电话',
            'tableindex' => 'tableCart_contact',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
         'web_hot' => array('des' => '热线电话',
            'tableindex' => 'tableCart_contact',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_mail' => array('des' => '电子邮件',
            'tableindex' => 'tableCart_contact',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_fax' => array('des' => '传真',
            'tableindex' => 'tableCart_contact',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
         'company-name' => array('des' => '企业名称',
            'tableindex' => 'langue',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_addr' => array('des' => '联系地址',
            'tableindex' => 'langue',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'web_working' => array('des' => '工作时间',
            'tableindex' => 'langue',
            'parentkey' => 'SiteConfig',
            'model' => 'input',
            'value' => ''
        ),
        'lbs_ak' => array('des' => '后台百度密钥',
            'tableindex' => 'tableCart_lbs',
            'model' => 'input',
            'value' => ''
        ),
        'lbs_frontak' => array('des' => '前台百度密钥',
            'tableindex' => 'tableCart_lbs',
            'model' => 'input',
            'value' => ''
        ),
       
        'aip_app_id' => array('des' => 'app_id',
            'tableindex' => 'tableCart_aip',
            'model' => 'hidden',
            'value' => ''
        ),
        'aip_api_key' => array('des' => 'api_key',
            'tableindex' => 'tableCart_aip',
            'model' => 'hidden',
            'value' => ''
        ),
        'aip_secret_key' => array('des' => 'secret_key',
            'tableindex' => 'tableCart_aip',
            'model' => 'hidden',
            'value' => ''
        ),
        'aip_spd' => array('des' => '语速',
            'tableindex' => 'tableCart_aip', 'des2' => '取值0-9，默认为5中语速',
            'model' => 'dropdown',
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 10),
            'value' => 5,
        ),
        'aip_pit' => array('des' => '音调',
            'tableindex' => 'tableCart_aip',
            //'des2' => '取值0-9，默认为5中语调',
            'model' => 'dropdown',
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 10),
            'value' => 5,
        ),
        'aip_vol' => array('des' => '语速',
            'tableindex' => 'tableCart_aip',
            //'des2' => '0-15',
            'model' => 'dropdown',
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 16),
            'value' => 5,
        ),
        'aip_per' => array('des' => '发音人选择',
            // 'des2' => ' 0为女声，1为男声，3为情感合成-度逍遥，4为情感合成-度丫丫，默认为普通女',
            'tableindex' => 'tableCart_aip',
            'model' => 'rdlist',
            'source' => array('sourcetyp' => 'hash', 'hash' => [0 => '女声', 1 => '男声', 3 => '度逍遥', 4 => '度丫丫']),
            'value' => 5,
        ),
        'validate_rule' => array(
            //array('lbs_cheweibi', 'number', '车位充足比例必须是数字', 1),
//            array('lbs_subway', 'number', '地铁站检索半径必须是数字', 1),
            array('web_list_pagesize', 'number', '后台分页记录必须是数字', 1),
            array('front_list_pagesize', 'number', '前台分页记录必须是数字', 1),
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
            'tableCart_contact' => '联系方式',
            'tableCart_email' => '邮件设置',
            'tableCart_wecat' => '微信设置',
            'tableCart_lbs' => '百度地图',
            'tableCart_aip' => '百度语音合成',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="网站系统配置">
    'SYSTEM' => array(
        'soft' => array('des' => '软件名称',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'short_name' => array('des' => '软件简称',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'company' => array('des' => '公司名称',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'syslogo' => array('des' => '系统LOGO',
            'tableindex' => 'tableCart_base',
            'model' => 'image',      
            'value' => '',
            'inputtype' => 'hidden'
        ),
        'version' => array('des' => '版本',
            'tableindex' => 'tableCart_base',       
            'model' => 'input',    
            'readonly' => 1,
            'value' => ''
        ),
        'siteurl' => array('des' => '开发者网站',
            'tableindex' => 'tableCart_developer',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'tel' => array('des' => '电话',
            'tableindex' => 'tableCart_developer',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'fax' => array('des' => '传真',
            'tableindex' => 'tableCart_developer',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'copyright' => array('des' => '版权',
            'tableindex' => 'tableCart_developer',
            'model' => 'input',
            'readonly' => 1,
            'value' => ''
        ),
        'login_code' => array('des' => '后台验证码',
            'tableindex' => 'tableCart_safe',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'lazyimg' => array('des' => '图片懒加载',
            'tableindex' => 'tableCart_safe',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'front_login_code' => array('des' => '前台验证码',
            'tableindex' => 'tableCart_safe',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'single_sign' => array('des' => '单点登录',
            'tableindex' => 'tableCart_safe',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'yesno',
            ),
        ),
        'access_token_expires' => array('des' => '令牌保持时间', 'des2' => '令牌保持时间，单位（秒）',
            'tableindex' => 'tableCart_safe',
            'model' => 'input',
            'readonly' => 0,
            'value' => ''
        ),
        'passsavetime' => array('des' => '登录保持', 'des2' => '登录保持时间，单位（秒）',
            'tableindex' => 'tableCart_safe',
            'model' => 'input',
            'readonly' => 0,
            'value' => ''
        ),
        'onlinereflash' => array('des' => '在线列表更新', 'des2' => '在线列表更新时间间隔，单位（秒）',
            'tableindex' => 'tableCart_safe',
            'model' => 'input',
            'readonly' => 0,
            'value' => ''
        ),
        'passovertime' => array('des' => '提示改密', 'des2' => '密码使用时间超出时提示，单位（天）',
            'tableindex' => 'tableCart_safe',
            'model' => 'input',
            'readonly' => 0,
            'value' => ''
        ),
        'passrule' => array('des' => '密码规则', 'des2' => '密码规则',
            'tableindex' => 'tableCart_safe',
            'model' => 'input',
            'readonly' => 0,
            'value' => ''
        ),      
        'blacklist' => array('des' => '敏感词', 'des2' => '敏感词',
            'tableindex' => 'tableCart_safe',
            'model' => 'text',
            'readonly' => 0,
            'value' => ''
        ),
        
        'mail_host' => array('des' => 'smtp服务器',
            'tableindex' => 'tableCart_email',
            'model' => 'input',  
            'value' => ''
        ),
        'mail_username' => array('des' => '邮箱名',
            'tableindex' => 'tableCart_email',
            'model' => 'input',       
            'value' => ''
        ),
        'mail_password' => array('des' => '邮箱密码',
            'tableindex' => 'tableCart_email',
            'model' => 'input',      
            'value' => ''
        ),
        'mail_from' => array('des' => '邮箱地址',
            'tableindex' => 'tableCart_email',
            'model' => 'input',        
            'value' => ''
        ),
        'mail_fromname' => array('des' => '发件人姓名',
            'tableindex' => 'tableCart_email',
            'model' => 'input',
          
            'value' => ''
        ),
        'mail_ishtml' => array('des' => 'HTML格式',
            'tableindex' => 'tableCart_email',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'mail_smtpauth' => array('des' => 'smtp认证',
            'tableindex' => 'tableCart_email',
            'model' => 'rdlist',
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'mail_charset' => array('des' => '邮件编码',
            'tableindex' => 'tableCart_email',
            'model' => 'input',
          
            'value' => ''
        ),
        'table_card' => array(
            "tableCart_base" => '系统设置',
            'tableCart_developer' => '开发者',
            'tableCart_safe' => '安全设置',
            'tableCart_email' => '邮件服务器',
        ),
    ),
    'DefaultClass' => array(
        'input' => "", //input-circle
        'autocomplete' => '',
        'password' => '',
        'rdlist' => 'group-T',
        'titlecls' => 'help-inline'//帮助提示样式
    ),
    'RUNSQL' => array(
        'sql' => array('des' => '输入SQL',
            'model' => 'text',
            'value' => ''
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="网站属性管理">
    'ATTRSCONFIG' => array(
        'tagmark' => array('des' => '键名',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'AttrsConfig',
            'model' => 'input',
            'value' => ''
        ),
        'tagvalue' => array('des' => '键值',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'AttrsConfig',
            'model' => 'input',
            'value' => ''
        ),
        'parentid' => array('des' => '上级键',
            'tableindex' => 'tableCart_base',
            'model' => 'tree',
            'search' => 'lay-search',
            'mod' => 'NotSelf', //FinalNode,all,NotSelf
            'listtopid' => 0,
            'listtopname' => '根键',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'sourcetyp' => 'dbmodel',
                'dbmodel' => '\Common\Gmodel\AtbModel',
            ),
            'value' => 0
        ),
        'verify' => array('des' => '验证条件',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'AttrsConfig',
            'model' => 'cklist',
            'verify' => '',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'verifyType',
            ),
            'value' => '',
        ),
        'tagtype' => array('des' => '属性类型',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'AttrsConfig',
            'model' => 'rdlist',
            'search' => 'lay-search',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'attrstatus',
            ),
            'value' => '1'
        ),
        'tagclass' => array('des' => '显示样式',
            'tableindex' => 'tableCart_base',
            'parentkey' => 'AttrsConfig',
            'model' => 'input',
            'value' => ''
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '0'
        ),
        'isshow' => array('des' => '启用',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'value' => '1',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'tagmark' => 'opcolse',
                'sourcetyp' => 'attrmap',
            ),
        ),
        'title' => array('des' => '标题',
            'tableindex' => 'langue',
//            'titletag' => 'title',
            'model' => 'input',
            'value' => ''
        ),
        'shorttitle' => array('des' => '短标题',
            'tableindex' => 'langue',
            'titletag' => 'shorttitle',
            'model' => 'input',
            'value' => ''
        ),
        'icon' => array('des' => '图标',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '图片',
            'tableindex' => 'langue',
            'model' => 'image',
            'value' => '',
            'inputtype' => 'hidden'
        ),

        'description' => array('des' => '描述',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => '',
        ),
        'verifymsg' => array('des' => '验证提示',
            'tableindex' => 'langue',
            'model' => 'input',
            'value' => '',
        ),
        'table_card' => array(
            'tableCart_base' => '基础参数',
        ),
    ),
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="广告位管理">
        'ADPANEL' => array(
        'position_id' => array(
            'des' => '广告类型',
            'model' => 'dropdown',
             'source' => array(
                'sourcetyp' => 'hash',
                'hash' => [1 => 'PC',
                    2 => 'MOB',
                    3 => 'APP'],
            ),
            'value' => 0,
        ),
        'ad_name' => array('des' => '名称',
            'model' => 'input',
            'value' => ''
        ),
        'position_mark' => array('des' => '位置标签',
            'model' => 'input',
            'value' => ''
        ),
        'ad_link' => array('des' => '链接',
            'model' => 'input',
            'value' => ''
        ),
        'ad_code' => array('des' => '图片',
            'inputtype' => 'hidden',
            'model' => 'image',
            'value' => ''
        ),
        'sortid' => array('des' => '排序',
            'model' => 'input',
            'value' => '0'
        ),
    ),
     //</editor-fold>
);

