<?php

/**
 * 租房管理
 * 最后修改时间：2017/10/20
 * 最后修改人：鲁承涛
 */
return array(
    //<editor-fold defaultstate="collapsed" desc="相册输入模板">
    'ZF_PHOTO' => array(
        'title' => array('des' => '标题',
            'model' => 'input',
            'value' => '',
        ),
        'phototype' => array('des' => '类型',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden', //hidden
            'readonly' => 1,
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'photo_type',
            ),
        ),
        'thumb' => array('des' => '封面照片',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => '',
        ),
        'desc' => array('des' => '简要描述',
            'model' => 'hidden',
            'value' => '',
        ),
    ),
    'ZF_PHOTODETAIL' => array(
        'thumb' => array('des' => '上传图片',
            'model' => 'mimage',
            'autopost' => 1, //自动提交
            'inputtype' => 'hidden',
            'value' => '',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="订单操作">
    'ORDER_OPERA' => array(
        'memo' => array('des' => '备注说明',
            'model' => 'text',
            'width' => 90,
            'value' => '',
        ),
        'imglist' => array('des' => '上传图片',
            'model' => 'mimage',
            'inputtype' => 'hidden',
            'value' => '',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="追加评价、回复">
    'ORDER_RJUDGE' => array(
        'imglist' => array('des' => '晒单图片',
            'model' => 'mimage',
            'inputtype' => 'hidden',
            'value' => '',
        ),
        'memo' => array('des' => '备注说明',
            'model' => 'text',
            'width' => 80,
            'value' => '',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="评价">
    'ORDER_JUDGE' => array(
        'score' => array('des' => '整体感受',
            'tableindex' => 'tableCart_base',
            'verify'=>'muststar',
            'readonly'=>1,
            'verifymsg'=>'请给整体感受评分',
            'model' => 'star',
            'source' => array('sourcetyp' => 'number', 'min' => 1, 'max' => 6),
            'value' => "",
        ),     
        'snug' => array('des' => '舒适度',
             'verifymsg'=>'请给舒适度评分',
             'verify'=>'muststar',
            'readonly'=>1,
            'model' => 'star',
            'source' => array('sourcetyp' => 'number', 'min' => 1, 'max' => 6),
            'value' => "",
        ),
        'facticity' => array('des' => '描述真实',
             'verifymsg'=>'请给描述真实评分',
             'verify'=>'muststar',
            'readonly'=>1,
            'model' => 'star',
            'source' => array('sourcetyp' => 'number', 'min' => 1, 'max' => 6),
            'value' => "",
        ),
        'attitude' => array('des' => '房东服务',
            'verifymsg'=>'请给房东服务评分',
            'verify'=>'muststar',
            'readonly'=>1,
            'model' => 'star',
            'source' => array('sourcetyp' => 'number', 'min' => 1, 'max' => 6),
            'value' => "",
        ),
        'imglist' => array('des' => '晒单图片',
            'model' => 'mimage',
            'inputtype' => 'hidden',
            'value' => '',
        ),
        'memo' => array('des' => '备注说明',
            'model' => 'text',
            'value' => '',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="房屋管理">
    'BUILDINGS' => array(
        'title' => array('des' => '房屋名称',
            'model' => 'input',
            'value' => '',
            'placeholder' => '请输入房屋名称',
            'tableindex' => 'tableCart_base',
        ),
//        'thumb' => array('des' => '封面照片',
//            'model' => 'image',
//            'inputtype' => 'hidden',
//            'value' => '',
//            'tableindex' => 'tableCart_base',
//        ),
        'photo' => array('des' => '相册',
            'model' => 'photo',
            'value' => '',
            'phototype' => 'building_cloumn',
            'tableindex' => 'tableCart_base',
        ),
        'address' => array(
            'des' => '房屋地址',
            'des2' => '双击输入框，自动定位地图坐标',
            'placeholder' => '请在地图上标出房屋所在位置',
            'model' => 'input',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'street' => array('des' => '街道',
            'model' => 'input',
            'placeholder' => '请输入房屋所在街道',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'streetcode' => array('des' => '街道编码',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'linkman' => array('des' => '联系人',
            'tableindex' => 'tableCart_base',
            'placeholder' => '我们该怎么称呼您',
            'model' => 'input',
            'readonly' => '3',
            'value' => '',
        ),
        'mobile' => array('des' => '移动电话',
            'placeholder' => '请输入您的手机号',
            'model' => 'input',
            'readonly' => '3',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
//        'streetcode' => array('des' => '街道',
//            'tableindex' => 'tableCart_base',
//            'model' => 'dropdown',
//            'listtopid' => '',
//            'listtopname' => '请选择',
//            'value' => '',
//            'source' => array(
//                'idfiled' => 'areacode',
//                'valuefiled' => 'areaname',
//                'table' => 'LbsSubregion',
//                'orderstr' => 'sortid asc',
//            ),
//        ),
        'housenumber' => array('des' => '门牌号码',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'addrtag' => array('des' => '商圈',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '',
        ),
        'loupanid' => array('des' => '所在小区',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden', //dropdown
            'listtopid' => '0',
            'listtopname' => '请选择',
            'value' => '',
            'source' => array(
                'idfiled' => 'id',
                'valuefiled' => 'title',
                'table' => 'ZfLoupan',
                'orderstr' => 'id asc',
            ),
        ),
        'nearest_subway' => array('des' => '最近地铁距离',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'nearest_subwayname' => array('des' => '最近地铁站名',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '',
        ),
        'regioncode' => array('des' => '行政区划',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'latitude' => array('des' => '纬度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'longitude' => array('des' => '经度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'polygons' => array('des' => '多边形',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'baidumap' => array('des' => '地图坐标',
            'model' => 'baidumap',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
//        'rentingmod' => array('des' => '租凭方式',
//            'tableindex' => 'tableCart_info',
//            'model' => 'cklist',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'Renttag',
//            ),
//            'value' => '',
//            'tableindex' => 'tableCart_info',
//        ),
        'paymod' => array('des' => '付款方式',
            'tableindex' => 'tableCart_info',
            'model' => 'cklist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Paymod',
            ),
            'value' => '',
        ),
        'min_rent' => array(
            'des' => '最低租金',
            'model' => 'input',
            'value' => '0',
            'tableindex' => 'tableCart_base',
        ),
        'max_rent' => array(
            'des' => '最高租金',
            'model' => 'input',
            'value' => '0',
            'tableindex' => 'tableCart_base',
        ),
        'gongnuan' => array('des' => '供暖方式',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gongnuan',
            ),
        ),
        'wuyie' => array('des' => '物业类型',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'wuyie_type',
            ),
            'value' => '',
        ),
        'vip' => array('des' => '使用等级',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'VIP',
            ),
            'value' => '',
        ),
//        'modid' => array('des' => '房源类型',
//            'titletag' => 'YunyinType',
//            'tableindex' => 'tableCart_info',
//            'model' => 'rdlist', //
//            'value' => '0',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'yunyintype',
//            ),
//        ),
        'floornumber' => array('des' => '所在楼层',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
//        'photoid' => array('des' => '相册',
//            'model' => 'phpotolist',
//            'value' => '',
//            'creapara' => array('phototype' => 3),
//            'windowtitle' => '相册管理',
//            'update' => '/ucent/photo/update',
//            'addnew' => '/ucent/photo/creat',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'orderstr' => 'id desc',
//                'extfiled' => ',thumb',
//                'table' => 'ZfPhoto',
//            ),
//            'tableindex' => 'tableCart_info',
//        ),
        'linkid' => array('des' => '联系方式',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden', //phpotolist
            'value' => '',
            // 'creapara'=>array('phototype'=>3),
            'windowtitle' => '联系人管理',
            'update' => '/ucent/linkman/update',
            'addnew' => '/ucent/linkman/creat',
            'source' => array('idfiled' => 'id',
                'valuefiled' => 'title',
                'orderstr' => 'is_default desc,id desc ',
                'extfiled' => ',thumb',
                'table' => 'ZfLinkman',
            ),
        ),
        'description' => array('des' => '详细介绍',
            'model' => 'text',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
            'tableCart_info' => '属性管理',
//            'tableCart_desc' => '详细介绍',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="出租客房管理">
    'ROOMS' => array(
        'title' => array('des' => '房间名称',
            'tableindex' => 'tableCart_base',
            'verify'=>'required',
            'model' => 'input',
            'value' => '',
        ),
        'tag' => array('des' => '标签',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'buildid' => array('des' => '所在房屋',
            'model' => 'dropdown',
            'verify'=>'required',
            'value' => '',
            'listtopid' => '',
            'readonly' => 0,
            'listtopname' => '选择楼宇',
            'source' => array('idfiled' => 'id',
                'valuefiled' => 'title',
                'orderstr' => 'id desc',
                'table' => 'ZfBuildings',
            ),
            'tableindex' => 'tableCart_base',
        ),
//        'thumb' => array('des' => '封面照片',
//            'model' => 'image',
//            'inputtype' => 'hidden',
//            'value' => '',
//            'tableindex' => 'tableCart_base',
//        ),
         'photo' => array('des' => '相册',
            'model' => 'photo',
            'value' => '',
            'phototype' => 'building_cloumn',
            'tableindex' => 'tableCart_base',
        ),
//        'photoid' => array('des' => '相册',
//            'model' => 'phpotolist',
//            'value' => '',
//            'creapara' => array('phototype' => 4),
//            'windowtitle' => '相册管理',
//            'update' => '/ucent/photo/update',
//            'addnew' => '/ucent/photo/creat',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'orderstr' => 'id desc',
//                'extfiled' => ',thumb',
//                'table' => 'ZfPhoto',
//            ),
//            'tableindex' => 'tableCart_desc',
//        ),
        'roomnum' => array('des' => '卧室',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
//             'ignore'=>'lay-ignore',//忽略美化
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 20),
            'value' => 0,
        ),
        'tingnum' => array('des' => '客厅',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
//            'ignore'=>'lay-ignore',//忽略美化
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 20),
            'value' => 0,
        ),
        'toiletnum' => array('des' => '洗手间',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
//             'ignore'=>'lay-ignore',//忽略美化
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 20),
            'value' => 0,
        ),
        'balcony' => array('des' => '阳台',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
//             'ignore'=>'lay-ignore',//忽略美化
            'source' => array('sourcetyp' => 'number', 'min' => 0, 'max' => 20),
            'value' => 0,
        ),
        'floor' => array('des' => '所在楼层',
            'tableindex' => 'tableCart_base',
             'verify'=>'number',
            //'placeholder'=>'所在楼层',
            'model' => 'input',
            'value' => '',
        ),
        'area' => array('des' => '总面积',
            'tableindex' => 'tableCart_base',
             'verify'=>'number',
            // 'placeholder'=>'房间面积',
            'model' => 'input',
            'value' => '',
        ),
        'dayhprice' => array('des' => '日租金',
            'tableindex' => 'tableCart_base',
             'verify'=>'number',
            'placeholder'=>'￥',
            'model' => 'input',
            'value' => '',
        ),
        'monthprice' => array('des' => '月租金',
            'tableindex' => 'tableCart_base',
             'verify'=>'number',
            'placeholder'=>'￥',
            'model' => 'input',
            'value' => '',
        ),
        'deposit' => array('des' => '押金',
            'tableindex' => 'tableCart_base',
             'verify'=>'number',
            'placeholder'=>'￥',
            'model' => 'input',
            'value' => '',
        ),
        'rentingtype' => array('des' => '出租类型',
            'tableindex' => 'tableCart_info',
            'verify'=>'mustradio',//输入验证类型
            'verifymsg'=>'必须选择一种出租类型',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'rentingtype',
            ),
            'value' => '',
        ),
        'wuyie' => array('des' => '物业类型',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'wuyie_type',
            ),
            'value' => '',
        ),
//        'rentingmod' => array('des' => '出租方式',
//            'tableindex' => 'tableCart_info',
//            'model' => 'cklist',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'Renttag',
//            ),
//            'value' => '',
//        ),
        'paymod' => array('des' => '付款方式',
            'tableindex' => 'tableCart_info',
            'verify'=>'mustcheck',//输入验证类型
            'verifymsg'=>'至少选中一种付款方式',//验证提示
            'model' => 'cklist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Paymod',
            ),
            'value' => '',
        ),
        'zhuangxiu' => array('des' => '装修类型',
            'tableindex' => 'tableCart_info',
            'model' => 'dropdown',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'RoomZhuangxiu',
            ),
            'value' => '',
        ),
        'gongnuan' => array('des' => '供暖方式',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gongnuan',
            ),
        ),
        'sebei' => array('des' => '客房设施',
            'tableindex' => 'tableCart_info',
            'model' => 'cklist', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'RoomSebei',
            ),
        ),
        'roomtype' => array('des' => '客房类型',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'RoomType',
            ),
        ),
        'roomface' => array('des' => '房屋朝向',
            'tableindex' => 'tableCart_info',
            'model' => 'dropdown', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'RoomFace',
            ),
        ),
        'attr' => array('des' => '属性',
            'tableindex' => 'tableCart_info',
            'model' => 'attrcklist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'RoomAttr',
            ),
            'value' => '0'
        ),
        'special' => array('des' => '房间特色',
            'tableindex' => 'tableCart_desc',
            'placeholder'=>'请用一句话描述房间的特色',
            'model' => 'input',
            'value' => '',
        ),
        'description' => array('des' => '详细描述',
            'tableindex' => 'tableCart_desc',
            'model' => 'text',
            'value' => '',
        ),
        'sellmod' => array('des' => '上架方式',
            'tableindex' => 'tableCart_desc',
            'model' => 'hidden',
            'value' => 1, //1 出租  2 新房  3 二手房
        ),
        'suitenum' => array('des' => '数量', //同类型房间数量
            'tableindex' => 'tableCart_desc',
            'model' => 'hidden',
            'value' => 1,
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
            'tableCart_info' => '属性管理',
            'tableCart_desc' => '文本说明',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="楼盘管理">
    'LOUPAN' => array(
        'title' => array('des' => '楼盘名称',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'proaddr' => array('des' => '项目地址',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'street' => array('des' => '街道',
            'model' => 'input',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'streetcode' => array('des' => '街道编码',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'regioncode' => array('des' => '行政区划',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'latitude' => array('des' => '纬度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'longitude' => array('des' => '经度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'polygons' => array('des' => '多边形',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'nearest_subway' => array('des' => '最近地铁距离',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => 0,
        ),
        'nearest_subwayname' => array('des' => '最近地铁站名',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden',
            'value' => '',
        ),
        'baidumap' => array('des' => '地图坐标',
            'model' => 'baidumap',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'developer' => array('des' => '开发商',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'manager' => array('des' => '物业公司',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'wuyielei' => array('des' => '小区类型',
            'tableindex' => 'tableCart_info',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'loupan_type',
            ),
            'value' => '',
        ),
        'tags' => array('des' => '标签',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden',
            'value' => '',
        ),
        'wuyiefei' => array('des' => '物业费',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => 0,
        ),
         'jiaofan' => array('des' => '交房时间',
            'tableindex' => 'tableCart_info',
            'model' => 'datepicker',
            'cls' => '',
            'dateformat' => array('type' => 'date', 'format' => 'yyyy-MM-dd'),
            'value' => '',
        ),       
//        'tag' => array('des' => '特色',
//            'tableindex' => 'tableCart_info',
//            'model' => 'cklist',
//            'source' => array('idfiled' => 'tagvalue',
//                'valuefiled' => 'title',
//                'sourcetyp' => 'attrmap',
//                'tagmark' => 'loupan_tag',
//            ),
//            'value' => '',
//        ),
        'chanquan' => array('des' => '产权年限',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
        'hushu' => array('des' => '规划户数',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
        'buildings' => array('des' => '楼宇总数',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
        'chewei' => array('des' => '车位数量',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
        'jianzhulei' => array('des' => '建筑类型',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden',
            'value' => 0,
        ),
        'gongshui' => array('des' => '供水方式',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden',
            'value' => 0,
        ),
        'zdmianji' => array('des' => '占地面积',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => 0,
        ),
        'mianji' => array('des' => '建筑面积',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => 0,
        ),
        'rongjilv' => array('des' => '容积率',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => 0,
        ),
        'lvhualv' => array('des' => '绿化率',
            'tableindex' => 'tableCart_info',
            'model' => 'input',
            'value' => '',
        ),
        'gongnuan' => array('des' => '供暖方式',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden', //
            'value' => '0',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'gongnuan',
            ),
        ),
        'gongdain' => array('des' => '供电方式',
            'tableindex' => 'tableCart_info',
            'model' => 'hidden',
            'value' => 0,
        ),
//        'thumb' => array('des' => '封面照片',
//            'model' => 'image',
//            'inputtype' => 'hidden',
//            'value' => '',
//            'tableindex' => 'tableCart_desc',
//        ),
        'photo' => array('des' => '相册',
            'model' => 'photo',
            'value' => '',
            'phototype' => 'loupan_cloumn',
            'tableindex' => 'tableCart_desc',
        ),
//        'photoid' => array('des' => '相册',
//             'model' => 'phpotolist',
//            'value' => '',
//            'creapara'=>array('phototype'=>2),
//            'windowtitle'=>'相册管理',
//            'update'=>'/ucent/photo/update',
//            'addnew'=>'/ucent/photo/creat',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'orderstr' => 'id desc',
//                'extfiled'=>',thumb',
//                'table' => 'ZfPhoto',
//            ),
//            'tableindex' => 'tableCart_desc',
//        ),
        'description' => array('des' => '详细介绍',
            'model' => 'text',
            'value' => '',
            'tableindex' => 'tableCart_desc',
        ),
        'table_card' => array(
            "tableCart_base" => '基础资料',
            'tableCart_info' => '属性管理',
            'tableCart_desc' => '详细介绍',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="省市区行政区划管理">
    'LBSREGION' => array(
        'province' => array('des' => '省',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'city' => array('des' => '市',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'region' => array('des' => '地区',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'host' => array('des' => '域名前缀',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'pgb' => array('des' => '省码',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'cgb' => array('des' => '市码',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'gbcode' => array('des' => '编码',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'alliance' => array('des' => '别名',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="乡镇街道管理">
    'LBSSUBREGION' => array(
        'areaname' => array('des' => '乡镇街道',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'areacode' => array('des' => '乡镇街道编码', 'des2' => '留空自动编码',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'gbcode' => array('des' => '地区编码',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'readonly' => 1,
            'value' => '',
        ),
        'sortid' => array('des' => '排序',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => 0,
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="房态管理">
    'ROOMFT' => array(
        'titleno' => array('des' => '房号',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'roomid' => array('des' => '房间',
            'model' => 'dropdown',
            'value' => '',
            'listtopid' => '',
            'readonly' => 0,
            'verify'=>'required',
            'listtopname' => '选择房间',
            'source' => array('idfiled' => 'id',
                'valuefiled' => 'title',
                'orderstr' => 'id desc',
                'table' => 'ZfRooms',
            ),
            'tableindex' => 'tableCart_base',
        ),
        'roomstatus' => array('des' => '当前房态',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'verify'=>'mustradio',//输入验证类型
            'verifymsg'=>'必须指定当前房态',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'room_status',
            ),
            'value' => '',
        ),
        'rent' => array('des' => '订单金额',
            'tableindex' => 'tableCart_base',
            'readonly' => 2,
            'model' => 'input',
            'value' => '',
        ),
        'deposit' => array('des' => '客户押金',
            'tableindex' => 'tableCart_base',
            'readonly' => 2,
            'model' => 'input',
            'value' => '',
        ),
        'paymod' => array('des' => '付款方式',
            'tableindex' => 'tableCart_info',
            'verify' => 'mustradio', //输入验证类型
            'verifymsg' => '至少选中一种付款方式', //验证提示
            'model' => 'rdlist',
            'source' => array(
                'idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Paymod',
                'filter' => ''//过滤参数
            ),
            'value' => '',
        ),
        'checkindata' => array('des' => '入住日期',
            'tableindex' => 'tableCart_base',
            'model' => 'datepicker',
            'dateformat' => array('type' => 'date', 'format' => 'yyyy-MM-dd','trancemat'=>'Y-m-d'),
            'cls' => '',
            'value' => '',
        ),
        'duedata' => array('des' => '到期时间',
            'tableindex' => 'tableCart_base',
            'model' => 'datepicker',
            'dateformat' => array('type' => 'date', 'format' => 'yyyy-MM-dd','trancemat'=>'Y-m-d'),
            'value' => '',
        ),
        'isrenew' => array('des' => '到期续租',
            'tableindex' => 1,
            'model' => 'rdlist',
            'readonly' => 2,
            'value' => 1,
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'opcolse',
            ),
        ),
        'table_card' => array(
            "tableCart_base" => '基础资料',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="联系人管理面板">
    'LINKMAN' => array(
        'title' => array('des' => '联系人',
            'tableindex' => 'tableCart_base',
            'placeholder' => '我们该怎么称呼您',
            'model' => 'input',
            'value' => '',
        ),
//        'lastname' => array('des' => '名字',
//            'tableindex' => 'tableCart_base',
//            'model' => 'input',
//            'value' => '',
//        ),
        'thumb' => array('des' => '头像',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'mobile' => array('des' => '移动电话',
            'placeholder' => '请输入您的手机号',
            'model' => 'input',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'tel' => array('des' => '固定电话',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'hottel' => array('des' => '热线电话',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'email' => array('des' => '电子邮件',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'address' => array('des' => '联系地址',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'memo' => array('des' => '备注',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'table_card' => array(
            "tableCart_base" => '基础资料',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="配套通用面板">
    'PEITAO_TONGYONG' => array(
        'templateid' => array('des' => '配套页面',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Peitao_Fuwu',
            ),
            'value' => '',
        ),
        'title_yemian' => array('des' => '页面标题',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'title_neirong' => array('des' => '内容标题',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'photo' => array('des' => '相册',
            'model' => 'photo',
            'value' => '',
            'phototype' => 'peitao_cloumn',
            'tableindex' => 'tableCart_base',
        ),
//        'thumb' => array('des' => '图片',
//            'model' => 'image',
//            'inputtype' => 'hidden',
//            'value' => '',
//            'tableindex' => 'tableCart_base',
//        ),
        'content' => array('des' => '具体内容',
            'model' => 'text',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'table_card' => array(
            "tableCart_base" => '配套详细',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="配套评价面板">
    'PEITAO_PINGJIA' => array(
        'templateid' => array('des' => '配套页面',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Peitao_Fuwu',
            ),
            'value' => '',
        ),
//        'photoid' => array('des' => '相册',
//             'model' => 'phpotolist',
//            'value' => '',
//            'creapara'=>array('phototype'=>5),
//            'windowtitle'=>'相册管理',
//            'update'=>'/ucent/photo/update',
//            'addnew'=>'/ucent/photo/creat',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'orderstr' => 'id desc',
//                'extfiled'=>',thumb',
//                'table' => 'ZfPhoto',
//            ),
//            'tableindex' => 'tableCart_desc',
//        ),
        'title_yemian' => array('des' => '标题',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'thumb' => array('des' => '图片',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
//        'title_neirong' => array('des' => '标题1',
//            'tableindex' => 'tableCart_base',
//            'model' => 'input',
//            'value' => '',
//        ),
//        'content' => array('des' => '具体内容',
//            'model' => 'text',
//            'value' => '',
//            'tableindex' => 'tableCart_base',
//        ),
        'table_card' => array(
            "tableCart_base" => '配套详细',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="配套介绍面板">
    'PEITAO_JIESHAO' => array(
        'templateid' => array('des' => '配套页面',
            'tableindex' => 'tableCart_base',
            'model' => 'rdlist',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'Peitao_Fuwu',
            ),
            'value' => '',
        ),
//        'photoid' => array('des' => '相册',
//             'model' => 'phpotolist',
//            'value' => '',
//            'creapara'=>array('phototype'=>5),
//            'windowtitle'=>'相册管理',
//            'update'=>'/ucent/photo/update',
//            'addnew'=>'/ucent/photo/creat',
//            'source' => array('idfiled' => 'id',
//                'valuefiled' => 'title',
//                'orderstr' => 'id desc',
//                'extfiled'=>',thumb',
//                'table' => 'ZfPhoto',
//            ),
//            'tableindex' => 'tableCart_desc',
//        ),
        'title_yemian' => array('des' => '标题',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => '',
        ),
        'photo' => array('des' => '相册',
            'model' => 'photo',
            'value' => '',
            'phototype' => 'peitao_cloumn',
            'tableindex' => 'tableCart_base',
        ),
//        'thumb' => array('des' => '图片',
//            'model' => 'image',
//            'inputtype' => 'hidden',
//            'value' => '',
//            'tableindex' => 'tableCart_base',
//        ),
//        'title_neirong' => array('des' => '标题2',
//            'tableindex' => 'tableCart_base',
//            'model' => 'input',
//            'value' => '',
//        ),
        'content' => array('des' => '具体内容',
            'model' => 'text',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'table_card' => array(
            "tableCart_base" => '配套详细',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="求租信息发布">
    'GBOOK' => array(
        'regionlist' => array('des' => '房屋名称',
            'model' => 'input',
            'value' => '',
            'placeholder' => '请在地图上点选期望房屋的位置',
            'tableindex' => 'tableCart_base',
        ),
        'loupanname' => array(
            'des' => '意向小区',
            'placeholder' => '请输入期望入住的小区',
            'model' => 'input',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'linkman' => array('des' => '您的称呼',
            'tableindex' => 'tableCart_base',
            'placeholder' => '我们该怎么称呼您',
            'model' => 'input',
            'readonly' => '3',
            'value' => '',
        ),
        'mobile' => array('des' => '移动电话',
            'placeholder' => '请输入您的手机号',
            'model' => 'input',
            'readonly' => '3',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'wuyie' => array('des' => '物业类型',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'wuyie_type',
            ),
            'value' => '',
        ),
        'regioncode' => array('des' => '行政区划',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'latitude' => array('des' => '纬度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'longitude' => array('des' => '经度',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'polygons' => array('des' => '多边形',
            'model' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'baidumap' => array('des' => '地图坐标',
            'model' => 'baidumap',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'min_rent' => array(
            'des' => '最低租金',
            'model' => 'input',
            'value' => '0',
            'tableindex' => 'tableCart_base',
        ),
        'max_rent' => array(
            'des' => '最高租金',
            'model' => 'input',
            'value' => '0',
            'tableindex' => 'tableCart_base',
        ),
        'linkid' => array('des' => '联系方式',
            'tableindex' => 'tableCart_base',
            'model' => 'hidden', //phpotolist
            'value' => '',
            // 'creapara'=>array('phototype'=>3),
            'windowtitle' => '联系人管理',
            'update' => '/ucent/linkman/update',
            'addnew' => '/ucent/linkman/creat',
            'source' => array('idfiled' => 'id',
                'valuefiled' => 'title',
                'orderstr' => 'is_default desc,id desc ',
                'extfiled' => ',thumb',
                'table' => 'ZfLinkman',
            ),
        ),
        'memo' => array('des' => '房屋要求',
            'model' => 'text',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'table_card' => array(
            "tableCart_base" => '基础参数',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="VIP模板">
    'MUBAN' => array(
        'title' => array('des' => '模板名称',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'thumb' => array('des' => '缩略图',
            'model' => 'image',
            'inputtype' => 'hidden',
            'value' => '',
            'tableindex' => 'tableCart_base',
        ),
        'path' => array('des' => '模板路径',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'price' => array('des' => '单买价格',
            'tableindex' => 'tableCart_base',
            'model' => 'input',
            'value' => ''
        ),
        'vip' => array('des' => '使用等级',
            'tableindex' => 'tableCart_base',
            'model' => 'dropdown',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'VIP',
            ),
            'value' => '',
        ),
        'table_card' => array(
            "tableCart_base" => 'VIP模板详细',
        ),
    ),
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="订单管理">
    'ORDER' => array(
        'orderno' => array('des' => '订单号',
            'placeholder' => '订单号',
            'model' => 'input',
            'value' => '',
        ),
        'userid' => array('des' => '用户ID',
            'model' => 'input',
            'value' => '',
        ),
        'roomid' => array('des' => '房间ID',
            'model' => 'input',
            'value' => '',
        ),
        'addtime' => array('des' => '下单时间',
            'model' => 'input',
            'value' => '',
        ),
        'ordertype' => array('des' => '订单类型',
            'model' => 'input',
            'value' => '',
        ),
        'price' => array('des' => '单价',
            'model' => 'input',
            'value' => '',
        ),
        'count' => array('des' => '数量',
            'model' => 'input',
            'value' => '',
        ),
        'livemod' => array('des' => '租凭类型',
            'model' => 'input',
            'value' => '',
        ),
        'status' => array('des' => '订单状态',
            'model' => 'dropdown',
            'listtopid' => '',
            'listtopname' => '订单状态',
            'source' => array('idfiled' => 'tagvalue',
                'valuefiled' => 'title',
                'sourcetyp' => 'attrmap',
                'tagmark' => 'order_status',
            ),
            'value' => '',
        ),
        'ispay' => array('des' => '支付状态',
            'model' => 'input',
            'value' => '',
        ),
    ),
    //</editor-fold>

    //看房管理
    'ROOMSHOW' => array(
        'roomid' => array('des' => '房间编号',
            'model' => 'input',
            'value' => '',
        ),
        'buildid' => array('des' => '所在楼宇',
            'model' => 'input',
            'value' => '',
        ),
        'userid' => array('des' => '用户ID',
            'model' => 'input',
            'value' => '',
        ),
        'shangjia' => array('des' => '商家ID',
            'model' => 'input',
            'value' => '',
        ),
        'regtime' => array('des' => '下单时间',
            'model' => 'input',
            'value' => '',
        ),
        'status' => array('des' => '订单状态',
            'model' => 'input',
            'value' => '',
        ),
    ),
    //租金管理
    'ZHUJING' => array(
        'roomid' => array('des' => '房间ID',
            'model' => 'input',
            'value' => '',
        ),
        'price' => array('des' => '租金',
            'model' => 'input',
            'value' => '',
        ),
        'pricetype' => array('des' => '租金类型',
            'model' => 'input',
            'value' => '',
        ),
        'deposit' => array('des' => '押金',
            'model' => 'input',
            'value' => '',
        ),
    ),
        //</editor-fold>
);
